# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               AI Monk
tagline:             'My musings on AI'
description:         'My musings on AI'
url:                 https://aimonk.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Anup Vasudevan
  email:             aimonk.info@gmail.com

# Custom vars
version:             1.0.0
